### PR TITLE
Fix: logging. "docker logs -f gsm-ts3" tail result in an error

### PR DESCRIPTION
**Pull request by MOD4EVER**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Review by sparklyballs — CHANGES_REQUESTED** [review]
You need to quote this line like so to prevent word splitting

"$(find /config/serverfiles/logs/*.log -printf '%p\n' |sort -r | head -n 2)"

**Comment by MOD4EVER** [comment]
@sparklyballs if you quote this line you get the following error:
`tail: cannot open '/config/serverfiles/logs/ts3server_..._0.log'$'\n''/config/serverfiles/logs/ts3server_..._1.log' for reading: No such file or directory`

  Please try it out.

**Comment by sparklyballs** [comment]
then we have an issue because unquoted it will break on any filenames with spaces etc

the purpose of the command is not to actually tail the log it's there because ts3 doesn't foreground and it's to trick s6 that it has.

**Comment by MOD4EVER** [comment]
@sparklyballs  the filenames has been gereneratate by teamspeak and have never spaces.

docker logs are be filled with trash... with your "purpose".
in additions it would be a good and useful feature for docker.

Could you please pursue my wish <3

**Comment by nightah** [comment]
@sparklyballs any chances of this being merged?
While I understand your explanation above, you could trick s6 via other means. It also looks like your original intent was to pipe the appropriate logs in for display via `docker logs -f containername`.

As @MOD4EVER has mentioned the TS log filename format has no spaces, as follows:
```
ts3server_2018-02-20__06_49_11.576851_0.log
ts3server_2018-02-20__06_49_11.576851_1.log
ts3server_2018-02-20__06_55_21.331280_0.log
ts3server_2018-02-20__06_55_21.331280_1.log
ts3server_2018-02-20__07_30_35.887704_0.log
ts3server_2018-02-20__07_30_35.887704_1.log
```
Unless Teamspeak decided to suddenly change the log formatting, accepting this change would not only get rid of the error that is presented every time the container is started, but also put meaningful logs alongside the container.

**Comment by sparklyballs** [comment]
the original intent was never about displaying the logs 

it was solely about making s6 believe the app was running in the foreground

introducing potentially breakable code just to tail a random log (there is more than one at any one time and when the next log file is made the logs will not be "meaningful" anymore) that can be easily viewed  in the mounted volume is not a viable option

**Comment by nightah** [comment]
@sparklyballs if that's the case then would you accept a PR that looks more like this:
```
	s6-setuidgid abc tail -F -q --pid="$(cat /config/serverfiles/ts3server.pid)" \
	/dev/null
```
To be rid of the error message being displayed?

**Pull request closed without merging**
